# Base Docker image
# FROM ubuntu:22.04 as base
FROM python:3.9-slim 


EXPOSE 8080
# Install dependencies
COPY requirements/requirements.in requirements.in
RUN pip install pip-tools flask && pip-compile -r requirements.in && pip install -r requirements.txt

# COPY inference script and pipeline config file
COPY inference_script.py inference_script.py
COPY pipeline_script.py pipeline_script.py
COPY configs/pipeline_config.yaml pipeline_config.yaml


ENTRYPOINT ["python", "inference_script.py"]
