# Grid Search configs

data:
  filename: 'data.csv'

clustering:
  k: 5
  resolution: 7

model: 



  # Model details
  max_depth: 4
  random_state: 0
  n_jobs: -1


  grid_search:
    max_depth: [4, 5]
    min_samples_leaf: [50, 75]
    n_estimators: [100, 150]

    cv: 3
    n_jobs: -1
    scoring: 'r2'

  model_filename: ''