ENDPOINT_NAME: busyness-model

hardware:
    training_machine_type: 'n1-standard-4'
    deployment_machine_type: 'n1-standard-4'

cloud:
  project_id: 'keen-airlock-455922-q4'
  region: 'us-central1'

deploy_model: TRUE
serving_image: 'us-docker.pkg.dev/vertex-ai/training/sklearn-cpu.1-6:latest'
