ENDPOINT_NAME: busyness-model-demo-final

hardware:
    training_machine_type: 'n1-standard-4'
    deployment_machine_type: 'n1-standard-4'

cloud:
  project_id: 'keen-airlock-455922-q4'
  region: 'us-central1'

MODEL_DIR: 'gs://skip-the-dishes-ml-model'
model_name: 'busyness_model_testing'
deploy_model: TRUE

# NOTE: we need to pin sklearn==1.6.0 due to container image not present
# DEPLOY_IMAGE: 'us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-5:latest'
DEPLOY_IMAGE: 'us-central1-docker.pkg.dev/keen-airlock-455922-q4/skip-the-dishesv2/test_image:inf'

DATA_URI: 'gs://busyness-data/final_dataset.csv'

