# Grid Search configs

data:
  filename: 'data/final_dataset.csv'
  # filename: 'data/data.csv'
  

  # train-val-test split
  test_size: 0.33
  random_state: 42
  # val_size: 0.15 # TODO: FIXME

clustering:
  k: 5
  resolution: 7




model: 
  model_filenmae: 'model.pkl'
  # Model details
  max_depth: 4
  random_state: 0
  n_jobs: -1


  grid_search:
    params:
      max_depth: [4, 5]
      min_samples_leaf: [50, 75]
      n_estimators: [100, 150]

    cv: 3
    n_jobs: -1
    scoring: 'r2'

  model_filename: ''