# Grid Search configs

data:
  filename: 'final_dataset.csv'
  filename_uri: 'gs://busyness-data/final_dataset.csv' # Set to None, to do local training
  bucket_name: busyness-data
  blob_path: final_dataset.csv

  processed_filename_uri: 'gs://busyness-data/processed_data'
  train_dataset_filename_uri: 'gs://busyness-data/processed_data/data_split/train_dataset'
  val_dataset_filename_uri: 'gs://busyness-data/processed_data/data_split/val_dataset'
  test_dataset_filename_uri: 'gs://busyness-data/processed_data/data_split/test_dataset'
  
  # filename_uri: None
  

  # train-val-test split
  test_size: 0.15
  random_state: 42
  val_size: 0.15 

clustering:
  k: 5
  resolution: 7




model: 
  model_filenmae: 'model.pkl'
  bucket_name: vasu-bucket
  blob_path: artifacts/model/model.pkl
  model_artifacts_uri: 'gs://vasu-bucket/artifacts'


  # Model parameters and hyperparameters
  max_depth: 4
  random_state: 0
  n_jobs: -1


  grid_search:
    params:
      max_depth: [4, 5]
      min_samples_leaf: [50, 75]
      n_estimators: [100, 150]

    cv: 3
    n_jobs: -1
    scoring: 'r2'


JOB_NAME: 'training_job_demo'
MODEL_DISPLAY_NAME: 'Busyness-model-demo'
TRAIN_IMAGE: us-central1-docker.pkg.dev/keen-airlock-455922-q4/skip-the-dishesv2/test_image:dev
TRAIN_COMPUTE: "n1-standard-4"
SYNC: True
START_REPLICA: 1
MAX_REPLICA: 1
# DEPLOY_IMAGE: 'us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-5:latest'
DEPLOY_IMAGE: us-central1-docker.pkg.dev/keen-airlock-455922-q4/skip-the-dishesv2/test_image:inf
PROJECT_ID: 'keen-airlock-455922-q4'
REGION: 'us-central1'
TRAIN_GPU: False
GPU: 
  GPU_NAME: NVIDIA_TESLA_T4
  TRAIN_NGPU: 1

