# Grid Search configs

data:
  filename: 'data/final_dataset.csv'
  filename_uri: 'gs://busyness-data/final_dataset.csv' # Set to None, to do local training
  # filename_uri: None
  

  # train-val-test split
  test_size: 0.33
  random_state: 42
  # val_size: 0.15 # TODO: FIXME

clustering:
  k: 5
  resolution: 7




model: 
  model_filenmae: 'model.pkl'
  # Model details
  max_depth: 4
  random_state: 0
  n_jobs: -1


  grid_search:
    params:
      max_depth: [4, 5]
      min_samples_leaf: [50, 75]
      n_estimators: [100, 150]

    cv: 3
    n_jobs: -1
    scoring: 'r2'

JOB_NAME: 'training_job_v2'
TRAIN_IMAGE: us-central1-docker.pkg.dev/keen-airlock-455922-q4/skip-the-dishesv2/test_image:dev
TRAIN_COMPUTE: "n1-standard-4"
DEPLOY_IMAGE: 'us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-5:latest'
PROJECT_ID: 'keen-airlock-455922-q4'
REGION: 'us-central1'
TRAIN_GPU: False
GPU: 
  GPU_NAME: NVIDIA_TESLA_T4
  TRAIN_NGPU: 1


