# name: Build and Push Development Image to GAR

# on:
#   workflow_run:
#     workflows:
#         - Linting and Formatting
#     types:
#         - completed
#   # push:
#   #   branches: [master]

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4

#     - name: Set up Cloud SDK
#       uses: google-github-actions/setup-gcloud@v2
#       with:
#         project_id: ${{ secrets.PROJECT_ID }}

#     - name: Authenticate
#       uses: google-github-actions/auth@v2
#       with:
#         credentials_json: ${{ secrets.GCP_SA_KEY }}

#     - name: Configure Docker
#       run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

#     - name: Build devlopment image
#       run: |
#         docker build . -t \
#         ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.IMAGE_NAME }}:dev

#     - name: Push development image
#       run: |
#         docker push \
#         ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.IMAGE_NAME }}:dev

#     # - name: Build production image
#     #   run: |
#     #     docker build -f Dockerfile.production . -t \
#     #     ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.IMAGE_NAME }}:prod

#     # - name: Push production image
#     #   run: |
#     #     docker push \
#     #     ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.IMAGE_NAME }}:prod


#     # - name: Build training image
#     #   run: |
#     #     docker build -f Dockerfile.training . -t \
#     #     ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.IMAGE_NAME }}:train

#     # - name: Push training image
#     #   run: |
#     #     docker push \
#     #     ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.IMAGE_NAME }}:train

    
    
