name: Deployment

on: 
  workflow_run:
    workflows:
      - Build and Push to GAR  # Name of the second workflow
      - Run Unit Tests
      - Linting and Formatting
    types:
      - completed
  # push:
  #   branches:
  #     - master
      
jobs:
  
  deploy-model:
    # needs: auth-docker-gcp
    runs-on: ubuntu-latest
    env: 
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      REGION: ${{ secrets.REGION }}
    container:
      # image:  "us-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:dev" #TODO: fix image
      image: us-central1-docker.pkg.dev/keen-airlock-455922-q4/skip-the-dishesv2/test_image:dev

      credentials:
        username: _json_key
        password: ${{ secrets.GAR_JSON_KEY }}  # Base64-encoded service account key

    steps:
    - uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Authenticate
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}


    - name: Configure Docker
      run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

    - name: Train and perform Batch Prediction
      run: |
         python training_vertex_ai.py

    # - name: Deploy model to Vertex AI
    #   run: |
    #      python pipeline_script.py   


