name: Deployment

on: [push]
  # master
  # push:
  #   branches: [master]

jobs:

  # auth-docker-gcp:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Set up Cloud SDK
  #     uses: google-github-actions/setup-gcloud@v2
  #     with:
  #       project_id: ${{ secrets.PROJECT_ID }}

  #   - name: Authenticate
  #     uses: google-github-actions/auth@v2
  #     with:
  #       credentials_json: ${{ secrets.GCP_SA_KEY }}

  #   - name: Configure Docker
  #     run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet
  deploy-model:
    # needs: auth-docker-gcp
    runs-on: ubuntu-latest
    env: 
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
    container:
      image:  us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
      credentials:
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}  # Base64-encoded service account key

    steps:
    - uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Authenticate
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}


    - name: Configure Docker
      run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet


