name: Linting and Formatting
on:
  push:
    branches: [master]

jobs:  
  lint-format:  
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: astral-sh/ruff-action@v1

        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: |
          pip install ruff bandit mypy black

      - name: Run Ruff
        run: ruff --check .
      
      # - name: Run Flake8
      #   run: flake8 .  # Check all files in repo
      
      - name: Run Mypy
        run: mypy .    # Type-check all Python files

      - name: Run Bandit Security scan 
        run:  bandit -r . -f txt
      
      - name: Run Black
        run: black . --check  # Check all files, no autofix