name: Linting and Formatting
on:
  push:
    branches: [main]

jobs:  
  lint-format:  
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: astral-sh/ruff-action@v1

        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: |
          pip install ruff bandit mypy black types-PyYAML

      - name: Run Ruff
        run: ruff check . --exit-zero
      
      - name: Run Mypy
        run: mypy . --explicit-package-bases --ignore-missing-imports    # Type-check all Python files

      - name: Run Bandit Security scan 
        run:  bandit -r . -f txt --exit-zero
      
      - name: Run Black
        run: black . --check  # Check all files, no autofix