name: Linting and Formatting
on: [push, pull_request]  

jobs:  
  lint-format:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
      - uses: actions/setup-python@v5  

      # Formatting (Black) and Linting (Ruff)  
      - uses: konstruktoid/action-pylint@v1.0.0  
        with:  
          args: "black --check . && ruff check ."  

  security-scan:  
    runs-on: ubuntu-latest  
    needs: lint-format  
    steps:  
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install safety bandit
      - run: safety check --full-report && bandit -r .