name: Linting and Formatting
on: [push, pull_request]  

jobs:  
  lint-format:  
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          pip install flake8 mypy bandit
      
      - name: Run Flake8
        run: flake8 .  # Check all files in repo
      
      - name: Run Mypy
        run: mypy .    # Type-check all Python files

      - name: Run Bandit Security scan 
        run:  bandit -r . -f txt
      
      - name: Run Pylint
        run: pylint **/*.py --exit-zero