name: Run Unit Tests

on:
  workflow_run:
    workflows:
      - Linting and Formatting
    types:
      - completed
    # push:
    #     branches:
    #         - master

jobs:
    unit-test:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
                python-version: '3.9'

        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install pytest pytest-cov

        - name: Run unit tests
          run: |
            pytest

        - name: Test code coverage with Pytest
          run: |
            pytest --cov=. tests/ 